### ISSUE TITLE
Synchronisation fails with "WARNING Parameters missing or invalid:1/1 cannot come before 1/1"

### ISSUE THREAD

**Issue by nigelcharman** [EcoNet-NZ/inaturalist-to-cams#75]
Stack trace:

```
Traceback (most recent call last):
  File "/home/runner/work/inaturalist-to-cams/inaturalist-to-cams/main.py", line 57, in <module>
    main()
  File "/home/runner/work/inaturalist-to-cams/inaturalist-to-cams/main.py", line 50, in main
    observation_counts = synchronise_inat_to_cams.synchroniser.sync_updated_observations()
  File "/home/runner/work/inaturalist-to-cams/inaturalist-to-cams/inat_to_cams/synchronise_inat_to_cams.py", line 52, in sync_updated_observations
    observations = func_timeout.func_timeout(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/runner/work/inaturalist-to-cams/inaturalist-to-cams/inat_to_cams/inaturalist_reader.py", line 1[26](https://github.com/EcoNet-NZ/inaturalist-to-cams/actions/runs/7692396401/job/20959237167#step:7:27), in get_matching_observations_updated_since
    client = pyinaturalist.iNatClient()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyinaturalist/client.py", line 114, in __init__
    self.session = session or ClientSession(**kwargs)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyinaturalist/session.py", line 121, in __init__
    super().__init__(  # type: ignore  # false positive
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/requests_cache/session.py", line 79, in __init__
    super().__init__(**get_valid_kwargs(super().__init__, kwargs))  # type: ignore
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/requests_ratelimiter/requests_ratelimiter.py", line 66, in __init__
    self.limiter = limiter or Limiter(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyrate_limiter/limiter.py", line [34](https://github.com/EcoNet-NZ/inaturalist-to-cams/actions/runs/7692396401/job/20959237167#step:7:35), in __init__
    self._validate_rate_list(rates)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pyrate_limiter/limiter.py", line 58, in _validate_rate_list
    raise InvalidParams(msg)
pyrate_limiter.exceptions.InvalidParams: Parameters missing or invalid:1/1 cannot come before 1/1
```

The first failing run is https://github.com/EcoNet-NZ/inaturalist-to-cams/actions/runs/7692270856.

**Comment by nigelcharman** [comment]
Seems to have been an issue in requests-ratelimiter 0.5.0 released an hour ago. Seems to be fixed in 0.5.1 released 20 minutes ago.

See https://pypi.org/project/requests-ratelimiter/#history
